name: MuteLabyVoice
version: '${project.version}'
main: com.namemc.mlv.MuteLabyVoice
api-version: 1.19
authors: [IrisJS]
commands:
  labymute:
    description: A command that mutes users on LabyMod's VoiceChat
    usage: /<command>
    permission: mlv.labymute
  labysetvolume:
    description: A command that sets the volume for the user's LabyMod VoiceChat
    usage: /<command>
    permission: mlv.labysetvolume