name: MuteLabyVoice
version: '${project.version}'
main: com.namemc.mlv.MuteLabyVoice
api-version: 1.19
authors: [IrisJS]
commands:
  labymute:
    description: A command that mutes users on LabyMod's VoiceChat
    usage: /<command> <length> <reason>
    permission: mlv.labymute